import { library } from "@fortawesome/fontawesome-svg-core";
import { faStar as faStarRegular } from "@fortawesome/free-regular-svg-icons";
import {
  faRobot,
  faUser,
  faUserCircle,
  faCog,
  faPalette,
  faQuestionCircle,
  faSignInAlt,
  faPlus,
  faChevronLeft,
  faChevronRight,
  faStar,
  faEllipsisH,
  faEdit,
  faTrashAlt,
  faChevronDown,
  faChevronUp, 
  faPaperclip,
  faMicrophone,
  faPaperPlane,
  faDownload,
  faComments,
  faSearch,
  faImage,
  faFile,
  faTimes,
  faBars,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faRobot,
  faUser,
  faUserCircle,
  faCog,
  faPalette,
  faQuestionCircle,
  faSignInAlt,
  faPlus,
  faChevronLeft,
  faChevronRight,
  faStar,
  faEllipsisH,
  faEdit,
  faStarRegular, 
  faTrashAlt,
  faChevronDown,
  faChevronUp,
  faPaperclip,
  faMicrophone,
  faPaperPlane,
  faDownload,
  faComments,
  faSearch,
  faImage,
  faFile,
  faTimes,
  faBars,


);

export default library;
